### ISSUE TITLE
0.6.3 build fails on jitpack

### ISSUE THREAD

**Issue by RubixDev** [Fallen-Breath/conditional-mixin#11]
The latest version (v0.6.3) fails to build on jitpack ([direct link to log](https://jitpack.io/com/github/Fallen-Breath/conditional-mixin/0.6.3/build.log)) because Java 17 was used but 21 is required. You already fixed this issue in 13e7dcc1b7e5005767625c309f4564937cd1e72f and I could depend on jitpack's build for that commit, but I'd rather only depend on released versions. Could you perhaps create a new 0.6.4 tag with that fix?

**Comment by Fallen-Breath** [comment]
done
