### ISSUE TITLE
Use java service loader to load the version checker service

### ISSUE THREAD

**Issue by SettingDust** [Fallen-Breath/conditional-mixin#8]
Architectury platform can't work across versions. It's only split the service into platforms, but not versions.
Service loader can let the developers use their own implementation to work with more loaders/versions.

For instance, https://github.com/SettingDust/preloading-tricks/tree/main/forge is targeting 2 version of forge

**Comment by Fallen-Breath** [comment]
What do you want to express?

- If this is an issue report, then please show what goes wrong in details
-  If this is a feature request, then please explains what do you want and why current design does not work

**Comment by SettingDust** [comment]
Feature Request

用 Java 的服务开发者可以自己支持指向的平台/版本
Architectury 的多平台设计是编译时而不是运行时，所以只能支持有限的几个平台且不能多版本

**Comment by Fallen-Breath** [comment]
> Architectury 的多平台设计是编译时而不是运行时

不同意，请求该观点出处

conditional mixin 的 mc 多版本兼容性与 architectury 架构无关，并且目前我也有若干个不同 mc版本的模组使用着本 conditional mixin，无任何问题

**Comment by Fallen-Breath** [comment]
若你遇到了 conditional mixin 无法按照预期在某个特定 mc 版本下运行的问题，请直接提交相关 issue

**Comment by SettingDust** [comment]
> 不同意，请求该观点出处

我，以及事实

**Comment by Fallen-Breath** [comment]
> > 不同意，请求该观点出处
> 
> 我，以及事实

若存在所述“事实”，请详细描述 conditional mixin 无法运行时的问题，包括 mod 列表、mc 版本，加载器类型等，如 https://github.com/Fallen-Breath/conditional-mixin/issues/8#issuecomment-2152106297 中所述

至此为止本 issue 尚未提供任何关于 conditional mixin 无法满足多 mc 版本兼容性的事实依据

**Comment by SettingDust** [comment]
只能兼容和在使用的 API 一致的，这是不需要证明的
所谓“多 MC 版本兼容”是建立在加载器模组版本信息获取的 API 没有变动的前提下
可以尝试在 1.12.2 Forge 里使用

**Comment by SettingDust** [comment]
> Architectury 的多平台设计是编译时而不是运行时，所以只能支持有限的几个平台且不能多版本

编译出来的 jar 是直接调用平台实现，这就是编译时

> 至此为止本 issue 尚未提供任何关于 conditional mixin 无法满足多 mc 版本兼容性的事实依据

这个 issue 是在说切换到 service loader 以允许开发者自行实现对应平台实现，而不是讨论哪个平台不兼容

**Comment by Fallen-Breath** [comment]
1.12.2 forge 不在 conditional-mixin 的支持范围内，conditional-mixin 无法在该版本中运行，是意料中的表现

如果你认为 conditional-mixin 未在 README 中显式标注出支持的 MC / 加载器版本的范围，你大可直接提出，而非晦涩地用与”README 缺少版本说明“无关的，”Architectury 框架不支持多 MC 版本“这一不准确的表述来提交 issue

由于已偏离本 issue 标题 / 介绍中所述内容，若需要提交有关”README 缺少版本说明“的问题，请新建 issue

**Comment by SettingDust** [comment]
> 这个 issue 是在说切换到 service loader 以允许开发者自行实现对应平台实现，而不是讨论哪个平台不兼容

**Comment by Fallen-Breath** [comment]
> > 这个 issue 是在说切换到 service loader 以允许开发者自行实现对应平台实现，而不是讨论哪个平台不兼容

不考虑支持
